let listaProductos = [
    {id: 1, marca: "DiatomiD", nombre: "Insecticida x 5Kg.", precio: 700, peso: 5, litros: null, img: '/Imagenes/Imgprod/insecticidax5kg.png'},
    {id: 2, marca: "DiatomiD", nombre: "Insecticida x 20Kg.", precio: 2000, peso: 20, litros: null, img: '/Imagenes/Imgprod/insecticidax20kg.png'},
    {id: 3, marca: "DiatomiD", nombre: "Insecticida micronizado x 18Kg.", precio: 2000, peso: 20, litros: null, img: '/Imagenes/Imgprod/micronizadox18kg.png'},
    {id: 4, marca: "DiatomiD", nombre: "Fertilizante x 25Kg.", precio: 1200, peso: 25, litros: null, img: '/Imagenes/Imgprod/fertilizatex25kg.png'},
    {id: 5, marca: "DiatomiD", nombre: "Absorbente x 25Kg.", precio: 1800, peso: 25, litros: null, img: '/Imagenes/Imgprod/absorbente.png'},
    {id: 6, marca: "Nutrigea", nombre: "Humus de lombriz líquido x 1L.", precio: 400, peso: null, litros: 1, img: '/Imagenes/Imgprod/humusx1L.jpeg'},
    {id: 7, marca: "Nutrigea", nombre: "Humus de lombriz líquido x 5L.", precio: 1800, peso: null, litros: 5, img: '/Imagenes/Imgprod/humusx5L.jpeg'},
    {id: 8, marca: "Nutrigea", nombre: "Humus de lombriz líquido x 20L.", precio: 5500, peso: null, litros: 20, img: '/Imagenes/Imgprod/humusx20L.jpg'},
    {id: 9, marca: "Nutrigea", nombre: "Humus de lombriz + Nitrogeno x 1L.", precio: 600, peso: null, litros: 1, img: '/Imagenes/Imgprod/nx1L.jpeg'},
    {id: 10, marca: "Nutrigea", nombre: "Humus de lombriz + Nitrogeno x 5L.", precio: 2300, peso: null, litros: 5, img: '/Imagenes/Imgprod/nx5L.jpeg'},
    {id: 11, marca: "Nutrigea", nombre: "Humus de lombriz + Nitrogeno x 20L.", precio: 6000, peso: null, litros: 20, img: '/Imagenes/Imgprod/nx20L.jpeg'},
    {id: 12, marca: "Nutrigea", nombre: "Humus de lombriz + Fosforo x 1L.", precio: 600, peso: null, litros: 1, img: '/Imagenes/Imgprod/px1L.jpeg'},
    {id: 13, marca: "Nutrigea", nombre: "Humus de lombriz + Fosforo x 5L.", precio: 2300, peso: null, litros: 5, img: '/Imagenes/Imgprod/px5L.jpeg'},
    {id: 14, marca: "Nutrigea", nombre: "Humus de lombriz + Fosforo x 20L.", precio: 6000, peso: null, litros: 20, img: '/Imagenes/Imgprod/px20L.jpeg'},
    {id: 15, marca: "Nutrigea", nombre: "Humus de lombriz + Potasio x 1L.", precio: 600, peso: null, litros: 1, img: '/Imagenes/Imgprod/kx1L.jpeg'},
    {id: 16, marca: "Nutrigea", nombre: "Humus de lombriz + Potasio x 5L.", precio: 2300, peso: null, litros: 5, img: '/Imagenes/Imgprod/kx5L.jpeg'},
    {id: 17, marca: "Nutrigea", nombre: "Humus de lombriz + Potasio x 20L.", precio: 6000, peso: null, litros: 20, img: '/Imagenes/Imgprod/kx20L.jpeg'},
    {id: 18, marca: "Nutrigea", nombre: "Bioestimulante x 1L.", precio: 500, peso: null, litros: 1, img: '/Imagenes/Imgprod/biox1L.jpeg'},
    {id: 19, marca: "Nutrigea", nombre: "Bioestimulanet x 5L.", precio: 2000, peso: null, litros: 5, img: '/Imagenes/Imgprod/biox5L.jpeg'},
    {id: 20, marca: "Nutrigea", nombre: "Enraizante x 1L.", precio: 600, peso: null, litros: 1, img: '/Imagenes/Imgprod/enraizantex1L.jpeg'},
    {id: 21, marca: "Nutrigea", nombre: "Enraizante x 5L.", precio: 2300, peso: null, litros: 5, img: '/Imagenes/Imgprod/enraizantex5L.jpeg'},
    {id: 22, marca: "Nutrigea", nombre: "Active Soil x 1L.", precio: 600, peso: null, litros: 1, img: '/Imagenes/Imgprod/activex1L.jpeg'},
    {id: 23, marca: "Nutrigea", nombre: "Active Soil x 5L.", precio: 2300, peso: null, litros: 5, img: '/Imagenes/Imgprod/activex5L.jpeg'},
    {id: 24, marca: "Nutrigea", nombre: "Active Soil x 20L.", precio: 6000, peso: null, litros: 20, img: '/Imagenes/Imgprod/activex20L.jpeg'}, 
]